/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proit.pe;

import com.proit.pe.dialog.AboutUsDialog;
import com.proit.pe.dialog.LoginDialog;
import com.proit.pe.dialog.SettingDialog;
import com.proit.pe.tabs.AddExpenditurePane;
import com.proit.pe.tabs.AddExpenditureTypePane;
import com.proit.pe.tabs.AddReceiptPane;
import com.proit.pe.tabs.AddReceiptTypePane;
import com.proit.pe.tabs.ListExpenditureTypesPane;
import com.proit.pe.tabs.ListExpendituresPane;
import com.proit.pe.tabs.ListReceiptTypesPane;
import com.proit.pe.tabs.ListReceiptsPane;
import java.awt.Component;
import java.awt.event.KeyEvent;

/**
 *
 * @author anhnn
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        setLocationRelativeTo(null);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        tbrAddExpenditure = new javax.swing.JButton();
        tbrListExpenditure = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        tbrAddReceipt = new javax.swing.JButton();
        tbrListReceipts = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        tbrLock = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        tbrCloseTab = new javax.swing.JButton();
        tpnBoard = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuLogin = new javax.swing.JMenuItem();
        mnuLogout = new javax.swing.JMenuItem();
        mnuLockup = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuSettings = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuAddExpenditureType = new javax.swing.JMenuItem();
        mnuListExpenditureTypes = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        mnuAddExpenditure = new javax.swing.JMenuItem();
        mnuListExpenditure = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        mnuAddReceiptType = new javax.swing.JMenuItem();
        mnuListReceiptTypes = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuAddNewReceipt = new javax.swing.JMenuItem();
        mnuListReceipts = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuContent = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuAboutUs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Personal Expenditure");
        setSize(new java.awt.Dimension(920, 556));

        jToolBar1.setRollover(true);

        tbrAddExpenditure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new_20.png"))); // NOI18N
        tbrAddExpenditure.setText("Add Expenditure");
        tbrAddExpenditure.setFocusable(false);
        tbrAddExpenditure.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrAddExpenditure.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrAddExpenditure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrAddExpenditureActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrAddExpenditure);

        tbrListExpenditure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/expenditure_32.png"))); // NOI18N
        tbrListExpenditure.setText("List Expenditure");
        tbrListExpenditure.setFocusable(false);
        tbrListExpenditure.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrListExpenditure.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrListExpenditure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrListExpenditureActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrListExpenditure);
        jToolBar1.add(jSeparator5);

        tbrAddReceipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new_20.png"))); // NOI18N
        tbrAddReceipt.setText("Add Receipt");
        tbrAddReceipt.setFocusable(false);
        tbrAddReceipt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrAddReceipt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrAddReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrAddReceiptActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrAddReceipt);

        tbrListReceipts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/receipt_32.png"))); // NOI18N
        tbrListReceipts.setText("List Receipts");
        tbrListReceipts.setFocusable(false);
        tbrListReceipts.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrListReceipts.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrListReceipts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrListReceiptsActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrListReceipts);
        jToolBar1.add(jSeparator6);

        tbrLock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lock_32.png"))); // NOI18N
        tbrLock.setText("Lock");
        tbrLock.setFocusable(false);
        tbrLock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrLock.setMinimumSize(new java.awt.Dimension(60, 60));
        tbrLock.setPreferredSize(new java.awt.Dimension(60, 60));
        tbrLock.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrLock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrLockActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrLock);
        jToolBar1.add(jSeparator7);

        tbrCloseTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit_20.png"))); // NOI18N
        tbrCloseTab.setText("Close Tab");
        tbrCloseTab.setFocusable(false);
        tbrCloseTab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrCloseTab.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrCloseTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrCloseTabActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrCloseTab);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 908, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        tpnBoard.addTab("Home", new javax.swing.ImageIcon(getClass().getResource("/icons/home_32.png")), jPanel1); // NOI18N

        jMenu1.setMnemonic(KeyEvent.VK_F);
        jMenu1.setText("File");

        mnuLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/login_20.png"))); // NOI18N
        mnuLogin.setText("Login");
        jMenu1.add(mnuLogin);

        mnuLogout.setText("Logout");
        mnuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(mnuLogout);

        mnuLockup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuLockup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lock_20.png"))); // NOI18N
        mnuLockup.setText("Lock");
        mnuLockup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLockupActionPerformed(evt);
            }
        });
        jMenu1.add(mnuLockup);
        jMenu1.add(jSeparator4);

        mnuSettings.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/setting_20.png"))); // NOI18N
        mnuSettings.setText("Settings");
        mnuSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSettingsActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSettings);
        jMenu1.add(jSeparator3);

        mnuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mnuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit_20.png"))); // NOI18N
        mnuExit.setMnemonic(KeyEvent.VK_X);
        mnuExit.setText("Exit");
        jMenu1.add(mnuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic(KeyEvent.VK_M);
        jMenu2.setText("Manager");

        mnuAddExpenditureType.setText("Add Expenditure Type");
        mnuAddExpenditureType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAddExpenditureTypeActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAddExpenditureType);

        mnuListExpenditureTypes.setText("List Expenditure Types");
        mnuListExpenditureTypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListExpenditureTypesActionPerformed(evt);
            }
        });
        jMenu2.add(mnuListExpenditureTypes);
        jMenu2.add(jSeparator8);

        mnuAddExpenditure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new_32.png"))); // NOI18N
        mnuAddExpenditure.setText("Add New Expenditure");
        mnuAddExpenditure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAddExpenditureActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAddExpenditure);

        mnuListExpenditure.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/expenditure_20.png"))); // NOI18N
        mnuListExpenditure.setText("List Expenditures");
        mnuListExpenditure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListExpenditureActionPerformed(evt);
            }
        });
        jMenu2.add(mnuListExpenditure);
        jMenu2.add(jSeparator10);

        mnuAddReceiptType.setText("Add Receipt Type");
        mnuAddReceiptType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAddReceiptTypeActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAddReceiptType);

        mnuListReceiptTypes.setText("List Receipt Types");
        mnuListReceiptTypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListReceiptTypesActionPerformed(evt);
            }
        });
        jMenu2.add(mnuListReceiptTypes);
        jMenu2.add(jSeparator2);

        mnuAddNewReceipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new_32.png"))); // NOI18N
        mnuAddNewReceipt.setText("Add New Receipt");
        mnuAddNewReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAddNewReceiptActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAddNewReceipt);

        mnuListReceipts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/receipt_20.png"))); // NOI18N
        mnuListReceipts.setText("List Receipts");
        mnuListReceipts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListReceiptsActionPerformed(evt);
            }
        });
        jMenu2.add(mnuListReceipts);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        mnuContent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/content_20.png"))); // NOI18N
        mnuContent.setText("Content");
        jMenu3.add(mnuContent);
        jMenu3.add(jSeparator1);

        mnuAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/about_20.png"))); // NOI18N
        mnuAboutUs.setText("About Us");
        mnuAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutUsActionPerformed(evt);
            }
        });
        jMenu3.add(mnuAboutUs);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpnBoard)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpnBoard)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbrAddExpenditureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrAddExpenditureActionPerformed
        AddExpenditurePane pane = new AddExpenditurePane(this);
        
        tpnBoard.addTab("Add Expenditure", pane);
        tpnBoard.setSelectedComponent(pane);
    }//GEN-LAST:event_tbrAddExpenditureActionPerformed

    private void tbrCloseTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrCloseTabActionPerformed
        
        int selectedIndex = tpnBoard.getSelectedIndex();
        if (selectedIndex >0){
            tpnBoard.remove(selectedIndex);
        }
    }//GEN-LAST:event_tbrCloseTabActionPerformed

    private void mnuAddExpenditureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAddExpenditureActionPerformed
        tbrAddExpenditureActionPerformed(evt);
    }//GEN-LAST:event_mnuAddExpenditureActionPerformed

    private void tbrListExpenditureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrListExpenditureActionPerformed
        ListExpendituresPane pane = new ListExpendituresPane(this);
        
        tpnBoard.addTab("List Expenditures", pane);
        tpnBoard.setSelectedComponent(pane);
    }//GEN-LAST:event_tbrListExpenditureActionPerformed

    private void mnuListExpenditureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListExpenditureActionPerformed
        tbrListExpenditureActionPerformed(evt);
    }//GEN-LAST:event_mnuListExpenditureActionPerformed

    private void tbrAddReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrAddReceiptActionPerformed
        AddReceiptPane pane = new AddReceiptPane();
        
        tpnBoard.addTab("Add Receipt", pane);
        tpnBoard.setSelectedComponent(pane);
    }//GEN-LAST:event_tbrAddReceiptActionPerformed

    private void mnuAddNewReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAddNewReceiptActionPerformed
        tbrAddReceiptActionPerformed(evt);
    }//GEN-LAST:event_mnuAddNewReceiptActionPerformed

    private void tbrListReceiptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrListReceiptsActionPerformed
        ListReceiptsPane pane = new ListReceiptsPane();
        
        tpnBoard.addTab("List Receipts", pane);
        tpnBoard.setSelectedComponent(pane);
    }//GEN-LAST:event_tbrListReceiptsActionPerformed

    private void mnuListReceiptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListReceiptsActionPerformed
        tbrListReceiptsActionPerformed(evt);
    }//GEN-LAST:event_mnuListReceiptsActionPerformed

    private void mnuAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutUsActionPerformed
        AboutUsDialog dialog = new AboutUsDialog(this, true);
        
        dialog.setVisible(true);
    }//GEN-LAST:event_mnuAboutUsActionPerformed

    private void mnuSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSettingsActionPerformed
        SettingDialog dialog = new SettingDialog(this, true);
        
        dialog.setVisible(true);
    }//GEN-LAST:event_mnuSettingsActionPerformed

    private void mnuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogoutActionPerformed
        LoginDialog dialog = new LoginDialog(this, true);
        
        dialog.setVisible(true);
    }//GEN-LAST:event_mnuLogoutActionPerformed

    private void mnuLockupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLockupActionPerformed
        mnuLogoutActionPerformed(evt);
    }//GEN-LAST:event_mnuLockupActionPerformed

    private void tbrLockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrLockActionPerformed
        mnuLogoutActionPerformed(evt);
    }//GEN-LAST:event_tbrLockActionPerformed

    private void mnuAddExpenditureTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAddExpenditureTypeActionPerformed
        AddExpenditureTypePane pane = new AddExpenditureTypePane(this);
        
        tpnBoard.addTab("Add Expenditure Type", pane);
        tpnBoard.setSelectedComponent(pane);
    }//GEN-LAST:event_mnuAddExpenditureTypeActionPerformed

    public void showListExpenditures(){
        tbrListExpenditureActionPerformed(null);
    }
    public void showEditExpenditure(int id){
        AddExpenditurePane pane = new AddExpenditurePane(this, id);
        
        tpnBoard.addTab("Edit Expenditure", pane);
        tpnBoard.setSelectedComponent(pane);
    }
    
    
    public void showListExpenditureTypes(){
        mnuListExpenditureTypesActionPerformed(null);
    }
    
    public void showEditExpenditureType(int id){
        AddExpenditureTypePane pane = new AddExpenditureTypePane(this, id);
        
        tpnBoard.addTab("Edit Expenditure Type", pane);
        tpnBoard.setSelectedComponent(pane);
    }
    
    private void mnuListExpenditureTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListExpenditureTypesActionPerformed
        ListExpenditureTypesPane pane = new ListExpenditureTypesPane(this);
        
        tpnBoard.addTab("List Expenditure Types", pane);
        tpnBoard.setSelectedComponent(pane);
    }//GEN-LAST:event_mnuListExpenditureTypesActionPerformed

    private void mnuAddReceiptTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAddReceiptTypeActionPerformed
        AddReceiptTypePane pane = new AddReceiptTypePane();
        
        tpnBoard.addTab("Add Receipt Type", pane);
        tpnBoard.setSelectedComponent(pane);
    }//GEN-LAST:event_mnuAddReceiptTypeActionPerformed

    private void mnuListReceiptTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListReceiptTypesActionPerformed
        ListReceiptTypesPane pane = new ListReceiptTypesPane();
        
        tpnBoard.addTab("List Receipt Types", pane);
        tpnBoard.setSelectedComponent(pane);
    }//GEN-LAST:event_mnuListReceiptTypesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
                
                LoginDialog dialog = new LoginDialog(null, true);
                
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnuAboutUs;
    private javax.swing.JMenuItem mnuAddExpenditure;
    private javax.swing.JMenuItem mnuAddExpenditureType;
    private javax.swing.JMenuItem mnuAddNewReceipt;
    private javax.swing.JMenuItem mnuAddReceiptType;
    private javax.swing.JMenuItem mnuContent;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuListExpenditure;
    private javax.swing.JMenuItem mnuListExpenditureTypes;
    private javax.swing.JMenuItem mnuListReceiptTypes;
    private javax.swing.JMenuItem mnuListReceipts;
    private javax.swing.JMenuItem mnuLockup;
    private javax.swing.JMenuItem mnuLogin;
    private javax.swing.JMenuItem mnuLogout;
    private javax.swing.JMenuItem mnuSettings;
    private javax.swing.JButton tbrAddExpenditure;
    private javax.swing.JButton tbrAddReceipt;
    private javax.swing.JButton tbrCloseTab;
    private javax.swing.JButton tbrListExpenditure;
    private javax.swing.JButton tbrListReceipts;
    private javax.swing.JButton tbrLock;
    private javax.swing.JTabbedPane tpnBoard;
    // End of variables declaration//GEN-END:variables
}
